const TennetBase='https://services-eu1.arcgis.com/WjozPuR5ROn6NZE8/ArcGIS/rest/services/TenneT_Assets_Hoogspanning/FeatureServer';
const PdokBase='https://api.pdok.nl/kadaster/brk-bestuurlijke-gebieden/ogc/v1/collections';
const STATION_ZOOM=8.7;
const map=L.map('map',{zoomControl:false,preferCanvas:false}).setView([52.18,5.35],7.35);
L.control.zoom({position:'bottomright'}).addTo(map);
L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap &copy; CARTO · Grid assets: TenneT TSO B.V. · Grenzen: PDOK/Kadaster'}).addTo(map);
const assetColor='#8293a3';const lineLayers=[],cableLayers=[],flowPaths=[],offshoreLayers=[],interconnectorLayers=[];let stationLayer,lastLive=null;
const countryNames={DE:'Duitsland',BE:'België',GB:'Groot-Brittannië',NO2:'Noorwegen',DK1:'Denemarken'};
function endpoint(layer){return `${TennetBase}/${layer}/query?where=1%3D1&outFields=*&outSR=4326&returnGeometry=true&f=geojson`}
function voltage(p){return p.SPANNINGSNIVEAU||'Onbekend'}function lineWeight(p){const v=voltage(p);return v==='380 kV'?4:v==='220 kV'?3.1:v==='150 kV'?2.3:1.6}
function popup(feature,type){const p=feature.properties||{};const name=p.OBJECTOMSCHRIJVING||p.STATIONID||type;const u=type==='Hoogspanningslijn'?'<small>Benutting: modelindicatie, zie gekleurde flowlaag</small>':'';return `<b>${name||type}</b><small>${voltage(p)} · ${p.STATUS||'status onbekend'}</small>${u}<small>Topologie: TenneT TSO B.V.</small>`}
async function getGeoJSON(layer){const r=await fetch(endpoint(layer));if(!r.ok)throw new Error(`TenneT laag ${layer}: HTTP ${r.status}`);return r.json()}
async function addNetherlandsContours(){try{const load=async collection=>{const r=await fetch(`${PdokBase}/${collection}/items?f=json&limit=100`);if(!r.ok)throw new Error(`PDOK ${collection}: HTTP ${r.status}`);return r.json()};const[land,provinces]=await Promise.all([load('landgebied'),load('provinciegebied')]);L.geoJSON(land,{style:{color:'#d9e2ea',weight:2.2,opacity:.8,fillColor:'#7d91a3',fillOpacity:.035},interactive:false}).addTo(map).bringToBack();L.geoJSON(provinces,{style:{color:'#7f93a5',weight:1,opacity:.48,fillOpacity:0,dashArray:'4 6'},interactive:false}).addTo(map).bringToBack()}catch(e){console.warn('Nederland-contouren niet geladen',e)}}
function coordsOf(feature){const g=feature.geometry;if(!g)return[];if(g.type==='LineString')return g.coordinates;if(g.type==='MultiLineString')return g.coordinates.flat();return[]}
function flowVector(){const f=lastLive?.border_flows||{};const anchors={DE:[-1,.05],BE:[-.25,.9],GB:[.95,.15],NO2:[.05,-1],DK1:[-.15,-.95]};let x=0,y=0,w=0;for(const[k,mwRaw]of Object.entries(f)){const a=anchors[k];if(!a)continue;const mw=Number(mwRaw)||0;x+=a[0]*mw;y+=a[1]*mw;w+=Math.abs(mw)}if(w<1)return[.15,.85];const n=Math.hypot(x,y)||1;return[x/n,y/n]}
function modeledFlow(feature){const c=coordsOf(feature);if(c.length<2)return 0;const a=c[0],b=c[c.length-1];let dx=b[0]-a[0],dy=b[1]-a[1];const n=Math.hypot(dx,dy)||1;dx/=n;dy/=n;const[fx,fy]=flowVector();const align=dx*fx+dy*fy;const scale={'380 kV':1,'220 kV':.76,'150 kV':.5,'110 kV':.36}[voltage(feature.properties)]||.3;return align*scale}
function modeledUtilization(feature){return Math.min(1,Math.abs(modeledFlow(feature))*.92+.08)}function utilizationColor(u){return u>=.8?'#ff5964':u>=.5?'#ffca59':'#49eca0'}
function flowStyle(feature){const q=modeledFlow(feature),u=modeledUtilization(feature),show=document.querySelector('#flowToggle')?.checked!==false;return{color:utilizationColor(u),weight:Math.max(3,lineWeight(feature.properties)),opacity:show?.96:0,dashArray:'8 10',lineCap:'round',interactive:false,className:q>=0?'flow-forward':'flow-reverse'}}
function addFlowOverlay(data,isCable=false){const layer=L.geoJSON(data,{style:f=>flowStyle(f)}).addTo(map);layer.eachLayer(l=>{l.__flowFeature=l.feature;l.__flowCable=isCable;flowPaths.push(l)})}
function refreshFlowStyles(){for(const l of flowPaths){l.setStyle(flowStyle(l.__flowFeature));const p=l.getElement?.();if(p){p.classList.remove('flow-forward','flow-reverse');p.classList.add(modeledFlow(l.__flowFeature)>=0?'flow-forward':'flow-reverse')}}refreshInterconnectors()}
function addLines(data,isCable=false){const target=isCable?cableLayers:lineLayers;const layer=L.geoJSON(data,{style:f=>({color:isCable?'#a8b4bf':assetColor,weight:lineWeight(f.properties),opacity:isCable?.55:.72,dashArray:isCable?'3 5':null,lineCap:'round'}),onEachFeature:(f,l)=>l.bindPopup(popup(f,isCable?'Ondergrondse kabel':'Hoogspanningslijn'),{className:'grid-popup'})}).addTo(map);target.push(layer);return data.features?.length||0}
function syncStationLOD(){if(!stationLayer)return;const show=map.getZoom()>=STATION_ZOOM;if(show){if(!map.hasLayer(stationLayer))stationLayer.addTo(map)}else if(map.hasLayer(stationLayer))map.removeLayer(stationLayer)}
function addStations(data){stationLayer=L.geoJSON(data,{style:f=>({color:'#aab8c4',weight:1.4,fillColor:'#152331',fillOpacity:.72}),onEachFeature:(f,l)=>{l.bindPopup(popup(f,'Hoogspanningsstation'),{className:'grid-popup'});const p=f.properties||{};if(p.STATIONID)l.bindTooltip(`${p.STATIONID} · ${voltage(p)}`,{permanent:false,direction:'top',className:'station-label'})}});syncStationLOD();return data.features?.length||0}
map.on('zoomend',syncStationLOD);
function offshoreIcon(cap){const size=Math.max(24,Math.min(38,21+Math.sqrt(Number(cap)||0)/5));return L.divIcon({className:'offshore-wind-icon-wrap',iconSize:[size,size],iconAnchor:[size/2,size/2],html:`<div class="offshore-wind-icon" style="width:${size}px;height:${size}px" aria-hidden="true"><span class="wind-rotor">✣</span><span class="wind-mast"></span></div>`})}
async function addOffshoreWind(){try{const r=await fetch(`data/offshore-wind.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const data=await r.json();for(const p of data.parks||[]){const marker=L.marker([p.lat,p.lon],{icon:offshoreIcon(p.capacity_mw)}).bindPopup(`<b>✣ ${p.name}</b><small>wind op zee · ${Math.round(p.capacity_mw).toLocaleString('nl-NL')} MW geïnstalleerd</small><small>Aanlanding: ${p.landing}</small>`,{className:'grid-popup'}).addTo(map);const cable=L.polyline([[p.lat,p.lon],[p.landing_lat,p.landing_lon]],{color:'#62d9ff',weight:2,opacity:.75,dashArray:'5 8',className:'offshore-flow'}).addTo(map);offshoreLayers.push(marker,cable)}}catch(e){console.warn(e)}}
function borderFlow(country){return Number(lastLive?.border_flows?.[country])||0}
function interconnectorUtil(ic,mw){return ic.capacity_mw?Math.min(1,Math.abs(mw)/ic.capacity_mw):Math.min(1,Math.abs(mw)/4000)}
function addInterconnectors(){for(const ic of window.NL_INTERCONNECTORS||[]){const mw=borderFlow(ic.country),u=interconnectorUtil(ic,mw),into=mw>=0;const line=L.polyline([ic.from,ic.to],{color:utilizationColor(u),weight:4,opacity:.95,dashArray:'12 10',className:into?'xborder-in':'xborder-out'}).bindPopup(`<b>${ic.name}</b><small>${ic.type}${ic.capacity_mw?` · ${ic.capacity_mw.toLocaleString('nl-NL')} MW nominale capaciteit`:''}</small><small id="ic-${ic.id}">${mw?`${Math.abs(mw).toLocaleString('nl-NL')} MW · ${into?'naar Nederland':'uit Nederland'}`:'Live flow wacht op ENTSO-E'}</small><small>${ic.note}</small>`,{className:'grid-popup'}).addTo(map);line.__ic=ic;interconnectorLayers.push(line)}}
function refreshInterconnectors(){for(const l of interconnectorLayers){const ic=l.__ic,mw=borderFlow(ic.country),u=interconnectorUtil(ic,mw),into=mw>=0;l.setStyle({color:utilizationColor(u)});const p=l.getElement?.();if(p){p.classList.remove('xborder-in','xborder-out');p.classList.add(into?'xborder-in':'xborder-out')}}}
function applyFilters(){const active=new Set([...document.querySelectorAll('.filters input[type=checkbox][value]:checked')].map(x=>x.value));for(const group of lineLayers)group.eachLayer(l=>{const show=active.has(voltage(l.feature.properties));l.setStyle({opacity:show?.72:0,weight:show?lineWeight(l.feature.properties):0})});const cableOn=document.querySelector('#cableToggle').checked;for(const group of cableLayers)group.eachLayer(l=>{const show=cableOn&&active.has(voltage(l.feature.properties));l.setStyle({opacity:show?.55:0,weight:show?lineWeight(l.feature.properties):0})});if(stationLayer)stationLayer.eachLayer(l=>{const show=active.has(voltage(l.feature.properties));l.setStyle({opacity:show?1:0,fillOpacity:show?.72:0})});for(const l of flowPaths){const enabled=active.has(voltage(l.__flowFeature.properties))&&(!l.__flowCable||cableOn);const s=flowStyle(l.__flowFeature);l.setStyle({opacity:enabled?s.opacity:0,weight:enabled?s.weight:0})}const offshoreOn=document.querySelector('#offshoreToggle')?.checked!==false;for(const l of offshoreLayers){if(offshoreOn){if(!map.hasLayer(l))l.addTo(map)}else if(map.hasLayer(l))map.removeLayer(l)}const crossOn=document.querySelector('#crossBorderToggle')?.checked!==false;for(const l of interconnectorLayers)l.setStyle({opacity:crossOn?.95:0,weight:crossOn?4:0})}
document.querySelectorAll('.filters input').forEach(el=>el.addEventListener('change',applyFilters));
function fmtMW(v){return Number.isFinite(v)?Math.round(v).toLocaleString('nl-NL'):'—'}function ageLabel(ts){if(!ts)return'—';const m=Math.max(0,Math.round((Date.now()-new Date(ts).getTime())/60000));return m<60?`${m} min`:`${Math.floor(m/60)}u ${m%60}m`}
function renderLive(data){lastLive=data;const source=document.querySelector('#liveSource'),updated=document.querySelector('#updated'),badge=document.querySelector('#liveBadge'),mixEl=document.querySelector('#generationMix'),flowsEl=document.querySelector('#borderFlows');if(!data||data.status!=='ok'){source.textContent=data?.status==='token-missing'?'token nodig':'niet beschikbaar';updated.textContent=data?.status==='token-missing'?'API-token nodig':'live data niet beschikbaar';badge.classList.add('stale');if(mixEl)mixEl.innerHTML='<div class="placeholder">Opwekmix niet beschikbaar</div>';if(flowsEl)flowsEl.innerHTML='<div class="placeholder">Grensstromen niet beschikbaar</div>';refreshFlowStyles();return}const measured=data.measured_at||data.generated_at,sources=(data.sources||[]).join(' + ');updated.textContent=`bijgewerkt ${ageLabel(measured)} geleden${sources?` · ${sources}`:''}`;badge.classList.remove('stale');const load=data.load_mw==null?NaN:Number(data.load_mw),gen=data.generation_mw==null?NaN:Number(data.generation_mw),net=data.net_import_mw==null?NaN:Number(data.net_import_mw);document.querySelector('#loadMW').textContent=fmtMW(load);document.querySelector('#genMW').textContent=fmtMW(gen);document.querySelector('#netMW').textContent=fmtMW(Math.abs(net));document.querySelector('#netLabel').textContent=Number.isFinite(net)&&net<0?'netto export MW':'netto import MW';document.querySelector('#age').textContent=ageLabel(measured);const mix=Array.isArray(data.generation_mix)?data.generation_mix:[];if(mixEl)mixEl.innerHTML=mix.length?mix.map(row=>`<div class="data-row"><span>${row.name}</span><strong>${fmtMW(Number(row.mw))}</strong></div>`).join(''):'<div class="placeholder">ENTSO-E opwekmix niet beschikbaar</div>';const flows=Object.entries(data.border_flows||{});if(flowsEl)flowsEl.innerHTML=flows.length?flows.sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])).map(([country,mw])=>{const n=Number(mw),into=n>=0;return`<div class="flow-row"><span class="country-name">${countryNames[country]||country}</span><span class="arrow ${into?'in':'out'}">${into?'import':'export'}</span><strong>${fmtMW(Math.abs(n))}</strong></div>`}).join(''):'<div class="placeholder">ENTSO-E-grensstromen niet geconfigureerd</div>';source.textContent=sources||'live';refreshFlowStyles()}
async function loadLive(){try{const r=await fetch(`data/live.json?t=${Date.now()}`,{cache:'no-store'});if(r.ok)renderLive(await r.json());else renderLive(null)}catch(e){renderLive(null)}}
async function boot(){const status=document.querySelector('#status');loadLive();addNetherlandsContours();try{const[overhead,cables,stations]=await Promise.all([getGeoJSON(2),getGeoJSON(3),getGeoJSON(5)]);document.querySelector('#lineCount').textContent=(addLines(overhead,false)+addLines(cables,true)).toLocaleString('nl-NL');addFlowOverlay(overhead,false);addFlowOverlay(cables,true);document.querySelector('#stationCount').textContent=addStations(stations).toLocaleString('nl-NL');await addOffshoreWind();addInterconnectors();applyFilters();status.textContent='Flow actief op alle verbindingen';setTimeout(()=>status.style.opacity=.55,2800)}catch(err){console.error(err);status.textContent='Kon TenneT-data niet laden'}}
function tick(){document.querySelector('#clock').textContent=new Intl.DateTimeFormat('nl-NL',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false,timeZone:'Europe/Amsterdam'}).format(new Date())}setInterval(tick,1000);setInterval(loadLive,60000);tick();boot();
const panelToggle=document.querySelector('#panelToggle'),sidebar=document.querySelector('#sidebar');if(panelToggle&&sidebar){panelToggle.addEventListener('click',()=>{const open=sidebar.classList.toggle('open');panelToggle.setAttribute('aria-expanded',String(open));panelToggle.textContent=open?'Sluiten':'Details';setTimeout(()=>map.invalidateSize(),220)});map.on('click',()=>{if(window.innerWidth<=700&&sidebar.classList.contains('open')){sidebar.classList.remove('open');panelToggle.setAttribute('aria-expanded','false');panelToggle.textContent='Details'}})}
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(err=>console.warn('Service worker niet geregistreerd',err)))}